# Generated by Django 4.2.11 on 2025-07-11 14:55

from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(error_messages={'unique': 'Ce NIF est déjà utilisé par un autre contribuable'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]+$', 'NIF invalide')], verbose_name="Numéro d'identification fiscale")),
                ('type_contribuable', models.CharField(choices=[('physique', 'Personne physique'), ('morale', 'Personne morale')], max_length=10)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s]{8,20}$', 'Numéro de téléphone invalide')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('notifier_retards', models.BooleanField(default=True, verbose_name='Notifier les retards de paiement')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='contribuables/identites/', verbose_name="Pièce d'identité")),
                ('reference', models.CharField(blank=True, editable=False, error_messages={'unique': 'Cette référence existe déjà'}, max_length=20, null=True, unique=True, verbose_name='Référence client')),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total payé')),
            ],
            options={
                'verbose_name': 'Contribuable',
                'verbose_name_plural': 'Contribuables',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_paiement', models.DateField()),
                ('date_echeance', models.DateField()),
                ('reference', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('mode_paiement', models.CharField(choices=[('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement'), ('CB', 'Carte Bancaire'), ('OM', 'Orange Money'), ('FM', 'Free Money'), ('WM', 'Wizale Money'), ('WA', 'Wave'), ('MOMO', 'MTN Mobile Money')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('quittance_generee', models.BooleanField(default=False)),
                ('fichier_quittance', models.FileField(blank=True, null=True, upload_to='quittances/')),
                ('taxe_redevance', models.CharField(blank=True, choices=[('patentes', 'Patentes'), ('taxe_licences', 'Taxe de licences'), ('propriete_batie', 'Propriété bâtie'), ('propriete_non_batie', 'Propriété non bâtie'), ('droit_mutation', 'Droit de mutation'), ('taxe_stationnement', 'Taxe de stationnement'), ('taxe_ordures', "Taxe d'enlèvement des ordures ménagères"), ('taxe_publicites', 'Taxe de publicités'), ('occupation_domaine', 'Occupation du domaine public')], help_text='Sélectionnez le type de taxe ou redevance', max_length=32, null=True, verbose_name='Taxe / Redevance')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion_contribuables.contribuable')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10)),
                ('details', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='gestion_contribuables.contribuable')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modifications',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddIndex(
            model_name='contribuable',
            index=models.Index(fields=['nif'], name='gestion_con_nif_cac85f_idx'),
        ),
        migrations.AddIndex(
            model_name='contribuable',
            index=models.Index(fields=['nom'], name='gestion_con_nom_f38946_idx'),
        ),
        migrations.AddIndex(
            model_name='contribuable',
            index=models.Index(fields=['actif'], name='gestion_con_actif_97ed80_idx'),
        ),
        migrations.AddConstraint(
            model_name='contribuable',
            constraint=models.UniqueConstraint(fields=('nif',), name='unique_nif'),
        ),
        migrations.AddConstraint(
            model_name='contribuable',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_reference'),
        ),
        migrations.AddConstraint(
            model_name='contribuable',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_contribuable_id'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_paiement_reference'),
        ),
    ]
