# Generated by Django 4.2.11 on 2025-07-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contribuables', '0001_initial'),
    ]

    operations = [
    ]
