# Generated by Django 4.2.11 on 2025-07-12 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contribuables', '0002_auto_20250711_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuable',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='nif',
            field=models.CharField(blank=True, error_messages={'unique': 'Ce NIF est déjà utilisé par un autre contribuable'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]+$', 'NIF invalide')], verbose_name="Numéro d'identification fiscale"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='taxe_redevance',
            field=models.CharField(blank=True, choices=[('patentes', 'Patentes'), ('taxe_licences', 'Taxe de licences'), ('propriete_batie', 'Propriété bâtie'), ('propriete_non_batie', 'Propriété non bâtie'), ('droit_mutation', 'Droit de mutation'), ('taxe_stationnement', 'Taxe de stationnement'), ('taxe_ordures', "Taxe d'enlèvement des ordures ménagères"), ('taxe_publicites', 'Taxe de publicités'), ('occupation_domaine', 'Occupation du domaine public')], max_length=32, null=True, verbose_name='Taxe / Redevance'),
        ),
    ]
