# Generated by Django 4.2.11 on 2025-07-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contribuables', '0003_contribuable_date_echeance_alter_contribuable_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuable',
            name='montant_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant net à payer'),
        ),
    ]
