# Generated by Django 4.2.11 on 2025-07-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contribuables', '0004_contribuable_montant_a_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuable',
            name='taxe_redevance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxe/Redevance'),
        ),
    ]
