# Generated by Django 4.2.11 on 2025-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contribuables', '0006_alter_paiement_taxe_redevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='reference',
            field=models.CharField(blank=True, editable=False, error_messages={'unique': 'Cette référence existe déjà'}, max_length=20, null=True, unique=True, verbose_name='Référence contribuable'),
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='taxe_redevance',
            field=models.CharField(blank=True, choices=[('patentes', 'Patentes'), ('taxe_licences', 'Taxe de licences'), ('propriete_batie', 'Propriété bâtie'), ('propriete_non_batie', 'Propriété non bâtie'), ('droit_mutation', 'Droit de mutation'), ('taxe_stationnement', 'Taxe de stationnement'), ('taxe_ordures', "Taxe d'enlèvement des ordures ménagères"), ('taxe_publicites', 'Taxe de publicités'), ('occupation_domaine', 'Occupation du domaine public')], max_length=32, null=True, verbose_name='Taxe/Redevance'),
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='type_contribuable',
            field=models.CharField(choices=[('physique', 'Personne physique'), ('morale', 'Personne morale')]),
        ),
    ]
