# Generated by Django 4.2.11 on 2025-08-31 19:29

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_contribuables', '0007_alter_contribuable_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=100, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la zone')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LocalisationContribuable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_maj', models.DateTimeField(auto_now=True, db_index=True)),
                ('contribuable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='gestion_contribuables.contribuable')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocalisation.zone', verbose_name='Zone associée')),
            ],
            options={
                'verbose_name': 'Localisation contribuable',
                'verbose_name_plural': 'Localisations contribuables',
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['nom'], name='geolocalisa_nom_55c3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['responsable'], name='geolocalisa_respons_0cf5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='localisationcontribuable',
            index=models.Index(fields=['zone'], name='geolocalisa_zone_id_9a0790_idx'),
        ),
        migrations.AddIndex(
            model_name='localisationcontribuable',
            index=models.Index(fields=['date_maj'], name='geolocalisa_date_ma_aed1cc_idx'),
        ),
    ]
