# Generated by Django 4.2.11 on 2025-08-31 19:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localisationcontribuable',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='localisationcontribuable',
            name='longitude',
        ),
        migrations.AddField(
            model_name='localisationcontribuable',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localisation'),
        ),
    ]
