# Generated by Django 5.2.5 on 2025-09-04 10:39

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalisation', '0002_remove_localisationcontribuable_latitude_and_more'),
    ]

    operations = [
        # Ajouter les nouveaux champs à Zone
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='zone',
            name='couleur',
            field=models.CharField(default='#0a384f', max_length=7, verbose_name="Couleur d'affichage"),
        ),
        migrations.AddField(
            model_name='zone',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Zone active'),
        ),
        migrations.AddField(
            model_name='zone',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),

        # Ajouter les nouveaux champs à LocalisationContribuable
        migrations.AddField(
            model_name='localisationcontribuable',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='localisationcontribuable',
            name='precision',
            field=models.CharField(
                choices=[('exact', 'Position exacte'), ('approximative', 'Position approximative'), ('zone', 'Zone générale')],
                default='approximative',
                max_length=20,
                verbose_name='Précision de la localisation'
            ),
        ),
        migrations.AddField(
            model_name='localisationcontribuable',
            name='source',
            field=models.CharField(
                choices=[('gps', 'GPS'), ('manuel', 'Saisie manuelle'), ('geocodage', "Géocodage d'adresse"), ('import', 'Import de données')],
                default='manuel',
                max_length=50,
                verbose_name='Source de la localisation'
            ),
        ),
        migrations.AddField(
            model_name='localisationcontribuable',
            name='verifie',
            field=models.BooleanField(default=False, verbose_name='Localisation vérifiée'),
        ),
        migrations.AddField(
            model_name='localisationcontribuable',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localisationcontribuable',
            name='date_maj',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
