services:
  - type: web
    name: retam-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn retam.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
